name: expense_repository
description: "handle expenses"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  fl_chart: ^1.0.0
  intl: ^0.20.2
  flutter_colorpicker: ^1.1.0

  # ✅ Compatible Firebase versions
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

